packages:
  - .

allowBuilds:
  esbuild: true
  protobufjs: true
  sharp: true
  tesseract.js: true
  unrs-resolver: true

onlyBuiltDependencies:
  - protobufjs
  - sharp
  - tesseract.js
  - unrs-resolver
